version: "3"

services:
  backend: &backend
    container_name: backend
    build:
      context: .
      dockerfile: DockerFile
    tty: true
    command: bash start.sh
    volumes:
      - .:/client
    ports:
      - 3030:3030
    depends_on:
      - db
    links:
      - db

  client: &client
    container_name: client
    build:
      context: ./client
      dockerfile: DockerFile
    command: bash start-client.sh
    tty: true
    stdin_open: true
    volumes:
      - .:/backend
    ports:
      - 3000:3000
    depends_on:
      - backend

  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USERNAME=postgres
    ports:
      - "5432:5432"

