default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: db
  username: postgres
  password: postgres

development:
  <<: *default
  database: erural_developer

test:
  <<: *default
  database: erural_developer_test

production:
  <<: *default
  database: erural_developer_prod